### ISSUE TITLE
Multi-tenancy Feedback

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#10]

**Comment by nbarbettini** [comment]
- [x] Is this contradictory? "For privacy and security purposes, its very important that each tenant have its own private data partition." and "Note - A Directory or Group can be added to multiple Organizations." **You could conceivably have multiple Organizations with their own private "Customer" Directories, but also an "Administrator" Directory that spans (is associated with) all of the Orgs. That being said, I've tweaked the language about multi-tenancy a bit (e.g. "data segmentation"). -JS**
- [x] **Modelling** - not sure if we want to go with the American form or the British/Canadian form here. It looks weird to me because I'm a Yankee. :smiley: (http://grammarist.com/spelling/model/) **We're going with the American spelling, y'all. -JS**
- [x] How to Create an Organization: "Groups and Accounts added to the Organization (e.g. A POST to /v1/organizations/:organizationId/groups) would fail." - might be helpful for newbies to tack on "until a default account store is added" or something.
- [x] Adding an Account Store to an Organization: first and second code block indenting is kinda extreme **This is the default spacing created by a tab or two. On reflection, it's going to look a lot better as two spaces than a whole tab..._sigh_ - JS**
- [x] Registering an Organization as an Account Store for an Application: as a (real) n00b to multi-tenancy in Stormpath, this confused me a bit. In this model, there would be a single application, and each tenant deployment of the application would be a different Organization added as an account store? This makes sense, but it might be helpful to concretely lay out this model in a short paragraph or diagram. **I've clarified that paragraph a bit, as well as the one at the top of the chapter. Hopefully this clarifies things. -JS**
