### ISSUE TITLE
Account Linking - Review

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#339]
Please leave any comments here.

**Comment by jhericks** [comment]
Is it useful/consistent to have a section called 'Update an Account Link' that just says, "Account links cannot be updated"?

_I do that just to make it clear that I didn't forget to mention it. - JS_

**Comment by jhericks** [comment]
"In order to unify all of these Accounts” is wordy.  Consider just “To unify these Accounts”.

**Comment by jhericks** [comment]
In the first part of 3.8: 

> Moreover, each Account would be associated with all of the other Accounts via Account Links.

They are probably not all linked with all the other ones, like a web.  More useful pattern and (I think) more realistic is that are linked in more of a 'star' pattern.  All of the mirror accounts would be linked to the cloud account, but there's not much use in linking the Facebook account directly to the Google account.

**Comment by jhericks** [comment]
Also from 3.8

> First and foremost, both Application’s and Organizations have Account Linking Policies, but Stormpath will always default to the Application’s Policy. This means that if you specify that you would like to log in to an Organization then that Organization’s Account Linking Policy will take precedence over the one for your Application.

First Application's should not be possessive.  

Also, the first sentence is confusing to me.  What does it mean to _always_ default to the Application's Policy and then immediately say how to not use the Application's policy? Maybe, "Both Applications and Organizations have Account Linking Policies.  Stormpath will default to the Application’s Policy if you don't log in to an Organization."

**Comment by jhericks** [comment]
Example login behavior, "With Existing, Linked Accounts, and no Automatic Account Linking" - actually if the accounts are linked, then automatic provisioning and matching property are irrelevant.

**Comment by jhericks** [comment]
In "How to Link Accounts Manually", you say, "this Account Link will appear in both of these Accounts’ `linkedAccounts` collections."  Revise to "this Account Link will appear in both of these Accounts' `accountLinks` collections."

**Comment by jhericks** [comment]
In "What's in Account Linking Policy", you say of Matching Property, "This defines what Account attribute should be used by Automatic Provisioning as a basis for account linking" but it's not Automatic Provisioning.  There are two separate things.  Automatic Provisioning will create an account if it can.  Matching Property will match to an existing account if it can.  If Matching Property is `email` AND Automatic Provisioning is ENABLED, the _first_ it will link to an existing account if it can and _if it cannot_ it will create a new account if it can.  

This has some some corner cases worth knowing, but perhaps too complicated to document clearly.  

First, if Automatic Provisioning is enabled, but creating a new account would cause a unique constraint - either because of an email clash or a username clash - then the account will not be created and the original, unlinked account will be returned from the login attempt.  

Second, if Automatic Provisioning is enabled and Matching Property is null, then you have configured yourself to behave exactly in the way that was so confusing a few days ago, where logging in with Facebook will create a cloud account, but if you delete the Facebook account and log in again, you will get no link because the cloud account already exists (so it won't get provisioned) and Matching Property is null (so there are no links automatically created to existing accounts).

**Comment by jhericks** [comment]
In "Policy Values and Outcomes", the table's first two rows are identical.  

<del>In my opinion, there are only two practical combinations: Disabled/null and Enabled/email.  Other configurations behave the way you describe, but if there were some way to call out the two 'most common' configurations, that might be better.  (Of course, there is no actual 'most common'  configuration yet.)</del> I see it in the very next section.

**Comment by jhericks** [comment]
In 3.8, Example Scenario 2, you say:

> In order to accomplish this, there a few things that need to happen:
> - the Application’s Account Linking Policy is left disabled (as it is by default)
> - the Organization Account Linking Policies are used to control Account Linking behavior
> - Every Organization has its own Directories, both Mirror and Cloud
> - The login page for this application must pass the user’s Organization href or nameKey with every login attempt.

To be pedantic about it, the application's Account Linking policy is irrelevant - it can be enabled or disabled, but will not be consulted.

Also for the third item, each organization can have its own directories, or can share some or all directories with other organizations however they want.  Take, for example, a case where three organizations all share the same mirror directories but each has it's own cloud directory as its default account store.  Then each account in the mirror directories could wind up with three links, one an account in each of the cloud directories.  I don't know if that configuration makes sense, but the point I'm making is that each organization having its own directories is not a pre-requisite for account linking scenario to work.

**Comment by jhericks** [comment]
Also, might be worth mentioning that other things besides POST'ing provider data to the application's accounts endpoint follow account linking as well.  Things like loginAttempts or token based authentication work the same way.

**Comment by jakubvul** [comment]
All feedback (except for the first comment) implemented here: https://github.com/stormpath/stormpath-documentation/commit/396bb89f8d870117492fbc351c0699480ffb8564
