### ISSUE TITLE
customData search

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#58]
customData search needs to be documented.

Probably makes the most sense to put it in the Account Mgmt chapter, near the "How to Store Additional User Information as Custom Data" section.

https://stormpath.atlassian.net/wiki/pages/viewpage.action?spaceKey=AM&title=Custom+Data+Search

**Comment by lhazlewood** [comment]
Just some clarifications: it is not yet fully functional (it does work, but at times may fail due to final operational changes occurring behind the scenes), but it should be documented.  It will be announced soon, and when it is announced, it will be announced as Beta.  The documentation for it shouldn't be released and available via docs.stormpath.com until that announcement is made.

**Comment by jakubvul** [comment]
Oh absolutely @lhazlewood. I just want to have it ready so that, when we do announce it, we have the REST Product Guide documentation to go with it. Until that time it will sit in its own branch and will absolutely not be pushed out into production.

**Comment by lhazlewood** [comment]
:+1:

**Comment by jakubvul** [comment]
Also need to create sections for the PHP and .NET Product Guides!
