### ISSUE TITLE
Quickstart Section Feedback

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#6]

**Comment by bretterer** [comment]
- [x] 'An Application resource called “My Application”' shouldn't it read 'Two Application resources: "My Application" and "Stormpath"  to avoid confusion when a new account is created **Good catch. Fixed. -JS**
- [x] Do we really require you to call `/tenant/current` to get the tenant id? Is it not available anywhere on the dashboard? **Yes**
- [x] Maybe make a note about leaving off the `?name=My%20Application` in the url string to get ALL applications **Done**
- [x] After creating accounts example, The part `You’ll notice here that this user Account has a directory href returned as well,` makes `directory` and `href` two different attributes **Fixed.**
- [x] The `7-Minute Tutorial.` goes to the products page **I've clarified that you'll have to click on an integration and then find a Quickstart**

**Comment by nbarbettini** [comment]
- [x] Quickstart: "This quickstart will get you up and running with Stormpath in about 7 minutes and give you a good initial feel for the Stormpath REST API." :+1: love this
- [x] Quickstart: "and now have... cURL installed on your system" - this sounds like it implies the First-Time Setup section helps you do this. **Good point, rephrased. -JS**
- [x] Quickstart: "“My Application Directory” is set as the default Directory for any new Accounts." - maybe clarify that this is the default directory for new accounts _added to My Application_? **Done -JS**
- [x] Retrieve your Application: "So if you’re building..." felt like an awkward shift from formal to informal dialog to me. (if that's what we're going for though, ignore!) **Fixed -JS**
- [x] Retrieve your Application: "We will also use the mock API Key from the First Time Set-Up chapter throughout this Quickstart:" - this was confusing to me on first read. It sounded like it was implying that you could use this API key to actually make requests, rather than just that it is being used in the examples. **Fixed -JS**
- [x] Retrieve your Application: The curl example to search for "My Application" uses `$API_KEY_ID:$API_KEY_SECRET`, but all the other examples use `$YOUR_API_KEY_ID:$YOUR_API_KEY_SECRET` **Actually, all the placeholders in this section are inconsistent with the rest of the doc. I'm going to go through and replace all of the $PLACEHOLDERS with :placeHolder -JS**
- [x] Retrieve your Application: Is there a stray single quote at the end of that line too? **Fixed-JS**
- [x] Retrieve your Application: The pattern of showing the curl command with placeholders, then showing the same commands with fake credentials, then showing the response seemed like extra noise to me. Could we skip the middle part? **Done**
- [x] Retrieve Your Application: If someone is following this quickstart and has never seen our API before, they might be confused as to why there are more attributes in a real-world response than are shown here. I was confused by this in our current quickstart when I first started playing with Stormpath. I figured it out pretty quick, but a small note that we're only showing a subset of the fields returned with a real request for brevity might be helpful to someone new. **Fixed. Put in a real response, and just put a [...] in the middle, which should make it pretty clear that I'm leaving out a section of it.**
- [x] Authenticate a User Account: "For example, if you used the tk421 username and Changeme1``" - there's some formatting weirdness going on here **Also fixed**

**Comment by jakubvul** [comment]
@bretterer You can't get the Tenant `href` from the Admin Console, plus this is the REST Guide, so even if you could I think we should still show you how to do it with REST API.

**Comment by nbarbettini** [comment]
@jakubswiatczak @bretterer +1, `GET /tenants/current` to get `302 /tenants/foo-bar` is the correct flow.

**Comment by SalaTzar** [comment]
Tom, does it makes to expose the tenant id in the console

**Comment by omgitstom** [comment]
@SalaTzar We are going to be revisiting onboarding in the UI, which might mean duplicating the quickstarts in the admin console so we can grab things like there API Key ID Secret / tenant href / application href to make it simple.
