### ISSUE TITLE
Account Management Feedback

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#7]

**Comment by nbarbettini** [comment]
- [x] Types of Directories: "Social Directories that pull-in" I don't think a hyphen is needed here. **Because you're [American](http://grammarist.com/usage/pullout-pull-out/). But that's fine, I'll go with that.**
- [x] The Provider Resource: Will there be more info here? This doesn't tell me much about why this resource exists. **Added some more info: "The Provider resource contains information about the source of the information found in its associated Directory resource. For example, if a Social Directory is created for GitHub, its Provider resource will contain information about your Github login integration (e.g. the OAuth Client and Secret required for Github login)." - JS**
- [x] Mirror Directories, the Agents resources, Installing Your Agent... this feels like it gets really far into the weeds. Is this the only place for this content to live? Unless I was interested in setting up an AD/LDAP integration, I would gloss over and scroll past all this stuff. **I had the same misgivings. Perhaps this belongs in the Reference section? -JS** @omgitstom ?
- [x] The Agent Resource: Agents URI - `/v1/agents/:directoryId` is this correct? At first glance, I thought it was supposed to be `/:agentId`, but now I'm thinking maybe this isn't a typo. If so, ignore! **It is correct. -JS**
- [x] "Agent URI" instead of "Agents URI" - for consistency with other sections?
- [x] How to Make a Mirror Directory: "(see above <provider-resource>)" - need a link here?
- [x] Social Directories, 3rd paragraph: Is this describing what happens automatically, or what the best practice is? (Not asking rhetorically, I really don't know. If our system automatically merges accounts from different login providers into a master account with `customData` references - that would be awesome :smile: ) **This is actually our default behaviour, yes. I will add some clarifying text.**
- [x] Social Directories, 5th paragraph: This might be pretty important information, but it feels buried here. **I highlighted it as a Note -JS**
- [x] Modeling User Hierarchies Using Groups: "in the Group’s `"description"` field" - no need for quotes inside the formatted code
- [x] Modeling User Hierarchies Using Groups: `groups?description=US%20East*` does our API translate `%20` to a slash? If so, that's cool. If not, I think it's a typo :smile:  **URL encoding replaces spaces with "+" or "%20". I'll put that into the doc.**
- [x] How to Create a Group: Code snippet following "Would yield this response:" has some formatting issues (first `{` isn't indented correctly)
- [x] How to Store Accounts in Stormpath: "Additionally, an Account may only exist in a single Directory and may be in multiple Groups owned by that Directory." - might be clearer if phrased as "An account may only exist in a single Directory, but may be in multiple Groups owned by that Directory."
- [x] Account Attributes: `status` - enabled, disabled, unverified - the code formatting isn't being applied to the second two
- [x] New Account Creation: "The basic steps for creating a new Account are covered in the :doc:" - link here? **For now this will point to the Quickstart, until the appropriate part of the Reference chapter is written. -JS**
- [x] Add an Existing Account to a Group: "This is done via a _groupMembership_*" - why the italics and asterisk?
- [x] Importing Accounts - perhaps this could be in a different page as well? (this one is starting to feel quite long)
- [x] Importing Accounts with MCF Hash Passwords: the second list item looks strangely indented.
- [x] How to Store Additional User Information as Custom Data: "With the following payload" code looks like it has an extra tab worth of indent.
- [x] How to Search Accounts: Attribute Search: the matching logic isn't correct here. `?email=path` would find all accounts where the `email` is _exactly_ "path". `?email=*path*` would find "path" inside any `email`.
- [x] How to Search Accounts: Datetime Search: needs a colon to be consistent with other sections above
- [x] The URL example isn't code formatted
- [x] Enable Password Reset Emails: Body: stray single quote at the end of the code block **Nate "Eagle Eyes" Barbettini**
- [x] Email Templates: resetEmailTemplate and resetSuccessEmailTemplate should be code formatted?
- [x] Verifying the Email Address: very last paragraph, "404 Not Found" should be code formatted for consistency with the rest of the docs
