### ISSUE TITLE
Authorization Feedback

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#9]

**Comment by nbarbettini** [comment]
- [x] First paragraph: needs period at end
- [x] I think that this introductory text could be split up a bit. It's useful info, but looks like a small wall of text. **It's about the same length as the next 3 paragraphs that follow. It also, to my mind, doesn't have any logical points at which to break it up... -JS**
- [x] What is Authorization: airport example might be clearer as: separate person later checks that you are allowed to actually board a **specific** plane."
- [x] Modeling Authorization in Stormpath: "This authorization data is extremely important to your overall security model." - this sentence feels strangely out of place? **Agreed. Changed to "In this section we will discuss how to model the authorization data which is extremely important to your overall security model." -JS**
- [x] How to Use Groups to Model Authorization Roles: "Note that we are not discussing a new type of Group resource here, but just pointing out that the Group resource can be used to model roles for the purposes of authorization." - I found this sentence confusing. I didn't think that the previous paragraphs were talking about a new type of group resource, but maybe that's because I'm already familiar with it. **I just wanted to make it clear that, even though I discuss a "user Group" and a "role Group", I'm only talking about two applications of the Group resource, and that they are not actually different types of Group. I'll add some clarifying language. -JS**
- [x] How to Use Groups to Model Authorization Roles: "having a Group called something like “administrators”..." - could be less wordy as "having a Group called "administrators"..."
- [x] Application-Wide Roles: "For more information about this, please see the [multi-tenancy section later in this guide]." - needs link
- [x] Application-Wide Roles: "while more information about Multi-Tenancy can be found [in the multi-tenancy section]" - needs link
- [x] How to Model Fine-Grained Permissions: "How is this flexibility possible? One word: customData." - I think this should either be `customData` or custom data. **Two words! -JS**
- [x] How to Model Fine-Grained Permissions: "And to find out all the different things you can do with customData please see the Product Guide" - link needs linkifying! :smile: 
- [x] Checking User Permissions: second and third code blocks have too much indent on first line
- [x] Checking User Permissions: "or to the `/customData` namespace" - _resource_ would be more appropriate than namespace here **Changed to "endpoint" -JS**
